name: "dms"
services:
  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app
    depends_on:
      - ocr
      - web
      - search
      - storage

  web:
    container_name: web
    image: node:20
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./web/public:/app/public
      - ./web/src:/app/src
      - ./web/package.json:/app/package.json
      - ./deps/web:/app/node_modules
    command: sh -c "npm install && HOST=0.0.0.0 CHOKIDAR_USEPOLLING=true npm run start"
    networks:
      - app
    depends_on:
      - ocr
      - search
      - storage

  auth:
    container_name: auth
    image: maven:3.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./auth:/app
      - ./deps/auth:/root/.m2/repository
    command: mvn spring-boot:run
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - keycloak

  storage:
    container_name: storage
    image: maven:3.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./storage:/app
      - ./deps/storage:/root/.m2/repository
    command: mvn spring-boot:run
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - keycloak
      - postgres
      - minio

  search:
    container_name: search
    image: maven:3.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./search:/app
      - ./deps/search:/root/.m2/repository
    command: mvn spring-boot:run
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - keycloak
      - postgres

  ocr:
    container_name: ocr
    image: python:3.9-slim
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y --no-install-recommends tesseract-ocr tesseract-ocr-rus tesseract-ocr-eng poppler-utils &&
        pip install --no-cache-dir 'watchdog[watchmedo]' -r /app/requirements.txt &&
        watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- python /app/main.py
      "
    volumes:
      - ./ocr:/app
    working_dir: /app
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build: psql
    image: dms-psql
    restart: always
    environment:
      POSTGRES_USER: ${DB_USR}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app

  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "${M_USR}"
      MINIO_ROOT_PASSWORD: "${M_PWD}"
    volumes:
      - ./files:/data
    command: server /data --console-address ":9090"
    ports:
      - "9090:9090"
    networks:
      - app

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.0
    platform: linux/amd64
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: $DB_USR
      KC_DB_PASSWORD: $DB_PWD
      KEYCLOAK_ADMIN: $KC_USR
      KEYCLOAK_ADMIN_PASSWORD: $KC_PASS
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: forwarded
      KC_HTTPS_CLIENT_AUTH: none
      KC_HEALTH_ENABLED: true
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - app
    restart: always

networks:
  app:
    driver: bridge