name: "dms"
services:
  proxy:
    container_name: proxy
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - app
    depends_on:
      - ocr
      - web
      - search
      - storage

  web:
    container_name: web
    build: ./web
    image: web
    expose:
      - "3000:3000"
    networks:
      - app
    depends_on:
      - ocr
      - search
      - storage

  storage:
    container_name: storage
    build: ./storage
    image: storage
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - postgres
      - minio

  search:
    container_name: search
    build: ./search
    image: search
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - postgres

  ocr:
    container_name: ocr
    build: ./ocr
    image: ocr
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USR}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: dms
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app

  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "${M_USR}"
      MINIO_ROOT_PASSWORD: "${M_PWD}"
    command: server /data --console-address ":9090"
    ports:
      - "9090:9090"
    networks:
      - app

networks:
  app:
    driver: bridge