########################################################################
server.port=8000
server.servlet.context-path=/api
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://infra.keycloak:8080/realms/dms/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://infra.keycloak:8080/realms/dms
########################################################################
keycloak.token-uri=http://infra.keycloak:8080/realms/dms/protocol/openid-connect/token
keycloak.client-id=adminClient
keycloak.client-secret=MVbfUlSGRxzwMcBsdb50nwAeoQ3vxm7g
########################################################################
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui