%%{init: {"theme": "default", "flowchart": {"fontSize": 9, "nodeSpacing": 25, "rankSpacing": 30}}}%%
flowchart TD
    A[HTTP-запрос] --> B[Анализ файла]
    B --> C[Хеш-файла]
    C --> D{Уже есть?}

    D -- Нет --> E[Сохранение в Minio]
    E --> F[Сохранение метаданных]
    F --> G[Рассылка события]
    G --> H[Открытие доступа]

    D -- Да --> I{Изменился?}
    I -- Да --> J[Создание новой версии]
    J --> F
    I -- Нет --> K[Файл уже есть. Версия: X]