%%{init: {"theme": "default", "flowchart": {"fontSize": 10, "nodeSpacing": 30, "rankSpacing": 40}}}%%
flowchart TD
    A[Получение HTTP-запроса\nс файлом] --> B[Валидация и извлечение\nпараметров]
    B --> C[Определение типа\nфайла]
    C --> D[Вычисление хеша]
    D --> E{Файл уже существует\nв системе?}

    E -- Нет --> F[Сохранение файла в Minio]
    F --> G[Сохранение хеша\nи метаданных\nв PostgreSQL]
    G --> H[Публикация события\nв RabbitMQ]
    H --> I[Оповещение других\nмодулей]
    G --> J[Открытие доступа\nк файлу]
    J --> K[Просмотр / Скачивание\n нужной версии]

    E -- Да --> L{Содержимое отличается?}
    L -- Да --> M[Создание новой версии файла]
    M --> G
    L -- Нет --> N[Пропуск сохранения, обновление метаданных]
    N --> H
