%%{init: {
  "theme": "default",
  "themeVariables": {
    "fontSize": "20px",
    "fontFamily": "Arial",
    "fontWeight": "bold"
  },
  "flowchart": {
    "nodeSpacing": 15,
    "rankSpacing": 25
  }
}}%%
flowchart TD
    classDef startStop fill:#f9f,stroke:#333,stroke-width:2px,color:#000,font-weight:bold
    classDef process fill:#e1efff,stroke:#668cff,stroke-width:1.5px,color:#000
    classDef decision fill:#fff9d6,stroke:#d1c04d,stroke-width:1.5px,color:#000

    Start([Старт]):::startStop
    Analyze[Анализ файла]:::process
    Hash[Хеш-файла]:::process
    SaveMinio[Сохранение в Minio]:::process
    Exists{Файл уже есть?}:::decision
    SaveVersion[Сохранение информации<br>о версии]:::process
    Changed{Файл изменился?}:::decision
    NewVersion[Создание новой версии]:::process
    Notify[Рассылка события]:::process
    Access([Открытие доступа]):::startStop
    Error([Ошибка: файл уже есть,<br>версия не изменилась]):::startStop
    End([Конец]):::startStop

    Start -- "<font face='Arial' color='black'></font>" --> Analyze
    Analyze -- "<font face='Arial' color='black'></font>" --> Hash
    Hash -- "<font face='Arial' color='black'></font>" --> SaveMinio
    SaveMinio -- "<font face='Arial' color='black'></font>" --> Exists

    Exists -- "<font face='Arial' color='black'>Нет</font>" --> SaveVersion
    Access -- "<font face='Arial' color='black'>Конец</font>" --> End

    Exists -- "<font face='Arial' color='black'>Да</font>" --> Changed
    Changed -- "<font face='Arial' color='black'>Да</font>" --> NewVersion
    NewVersion -- "<font face='Arial' color='black'></font>" --> SaveVersion
    SaveVersion -- "<font face='Arial' color='black'></font>" --> Notify
    Notify -- "<font face='Arial' color='black'></font>" --> Access

    Changed -- "<font face='Arial' color='black'>Нет</font>" --> Error
    Error -- "<font face='Arial' color='black'>Конец</font>" --> End
