########################################################################
server.port=8000
server.servlet.context-path=/storage
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KC_HOST:localhost}:${KC_PORT:8080}/realms/dms/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KC_HOST:localhost}:${KC_PORT:8080}/realms/dms
########################################################################
minio.endpoint=http://infra.minio:9000
minio.access-key=minio
minio.secret-key=minio123
minio.bucket=files-pool
########################################################################

