%%{init: {"theme": "default", "flowchart": {"fontSize": 9, "nodeSpacing": 25, "rankSpacing": 30}}}%%
flowchart TD
    A[HTTP-запрос] --> B[Анализ файла]
    B --> C[Вычисление хеша файла]
    C --> D{Файл уже есть?}

    D -- Нет --> E[Сохранить в Minio]
    E --> F[Сохранить хеш/метаданные]
    F --> G[Обработка событий]
    G --> H[Доступ к файлу]

    D -- Да --> I{Изменился?}
    I -- Да --> J[Новая версия]-->F
    I -- Нет --> K[Обновить метаданные] -->G