%%{init: {
  "theme": "default",
  "themeVariables": {
    "fontSize": "20px",
    "fontFamily": "Arial",
    "fontWeight": "bold"
  },
  "flowchart": {
    "nodeSpacing": 15,
    "rankSpacing": 25
  }
}}%%
flowchart TD
    classDef startStop fill:#f9f,stroke:#333,stroke-width:2px,color:#000,font-weight:bold
    classDef process fill:#e1efff,stroke:#668cff,stroke-width:1.5px,color:#000
    classDef decision fill:#fff9d6,stroke:#d1c04d,stroke-width:1.5px,color:#000

    Start([Старт]):::startStop
    Analyze[Анализ<br>файла]:::process
    Hash[Вычисление<br>хеш-суммы<br>файла]:::process
%%    SaveMinio[Сохранение в Minio]:::process
    Exists{Файл уже<br>есть?}:::decision
    SaveVersion[Сохранение<br>информации<br>о версии]:::process
    Changed{Файл<br>изменился?}:::decision
    NewVersion[Создание<br>новой<br>версии]:::process
    Notify[Рассылка<br>события]:::process
    Access([Открытие доступа]):::startStop
    Error([Ошибка: файл уже есть,<br>версия не изменилась]):::startStop
    End([Конец]):::startStop
    Start -- "<font face='Arial' color='black'></font>" --> Analyze
    Analyze -- "<font face='Arial' color='black'></font>" --> Hash
    Hash -- "<font face='Arial' color='black'></font>" --> Exists
    Exists -- "<font face='Arial' color='black'>Нет</font>" --> SaveDocument
    Exists -- "<font face='Arial' color='black'>Да</font>" --> Changed
    Changed -- "<font face='Arial' color='black'></font>" --> NewVersion
%%    Exists -- "<font face='Arial' color='black'>Нет</font>" --> NewVersion
%%    Access -- "<font face='Arial' color='black'>Конец</font>" --> End
%%

%%    Changed -- "<font face='Arial' color='black'>Да</font>" --> NewVersion

%%    SaveVersion -- "<font face='Arial' color='black'></font>" --> Notify
%%    Notify -- "<font face='Arial' color='black'></font>" --> Access
%%
%%    Changed -- "<font face='Arial' color='black'>Нет</font>" --> Error
%%    Error -- "<font face='Arial' color='black'>Конец</font>" --> End
