########################################################################
server.port=8080
server.servlet.context-path=/search
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KC_HOST:localhost}:${KC_PORT:8080}/realms/dms/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KC_HOST:localhost}:${KC_PORT:8080}/realms/dms
########################################################################
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/dms
spring.datasource.username=${DB_USR:postgres}
spring.datasource.password=${DB_PWD:sa}
spring.jpa.hibernate.ddl-auto=update
########################################################################